# Generated by Django 5.0.4 on 2024-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_carrito_total_alter_carritoitem_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
