# Generated by Django 5.0.4 on 2024-04-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_carritoitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
