# Generated by Django 5.0.4 on 2024-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_carrito_total_carritototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.ManyToManyField(to='tienda.carritototal'),
        ),
    ]
