# Generated by Django 5.0.4 on 2024-04-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
